
version = 0.1
[default.deploy.parameters]
stack_name = "JavaDEMOTEST"
resolve_s3 = true
s3_prefix = "JavaDEMOTEST"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "SecurityGroupId=\"\" Subnet1Id=\"\" Subnet2Id=\"\" DatabaseSecretName=\"\" DatabaseEndpoint=\"\""
image_repositories = []
profile = ""
