
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
 Function:
  Timeout: 30
  Environment:
   Variables:
    POWERTOOLS_SERVICE_NAME: JavaDEMOTEST

Parameters:
 SecurityGroupId:
  Description: Security Group for the application
  Type: String
 Subnet1Id:
  Description: Subnet Id for the first subnet
  Type: String
 Subnet2Id:
  Description: Subnet Id for the second subnet
  Type: String
 DatabaseSecretName:
  Description: The name of the secret holding database credentials
  Type: String
 DatabaseEndpoint:
  Description: The endpoint of the database
  Type: String

 #db credentials  to be passed from github secrets.
 DatabaseUrl:
  Type: String
  Description: Database connection URL
  NoEcho: true
 DatabaseUsername:
   Type: String
   Description: Database username
   NoEcho: true
 DatabasePassword:
   Type: String
   Description: Database password
   NoEcho: true
 SpringMailUsername:
  Type: String
  Description:  username for email sending
  NoEcho: true
 SpringMailPassword:
  Type: String
  Description: password for email sending
  NoEcho: true

Resources:
 LambdaProxy:
  Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
  Properties:
   CodeUri: .
   Handler: qucoon.mod.SpringServerless.lambda.LambdaProxy::handleRequest
   Runtime: java17
   AutoPublishAlias: production
   Role: arn:aws:iam::992382810653:role/lambdaRole
   SnapStart:
    ApplyOn: PublishedVersions
   Architectures:
    - x86_64
   MemorySize: 1024
   Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
    Variables:
     JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1 # More info about tiered compilation https://aws.amazon.com/blogs/compute/optimizing-aws-lambda-function-performance-for-java/
     #this is referencing the parameters we passed from the github screts
     DB_URL: !Ref DatabaseUrl
     DB_USERNAME: !Ref DatabaseUsername
     DB_PASSWORD: !Ref DatabasePassword
     SPRING_MAIL_USERNAME: !Ref SpringMailUsername
     SPRING_MAIL_PASSWORD: !Ref SpringMailPassword
   Events:
    HelloWorld:
     Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
     Properties:
      Path: /{proxy+}
      Method: ANY
      RestApiId: !Ref HelloWorldApi
 HelloWorldApi:
  Type: AWS::Serverless::Api
  Properties:
   StageName: api

Outputs:
 MyApiId:
  Description: 'API Gateway ID'
  Value: !Sub "https://${HelloWorldApi}.execute-api.${AWS::Region}.amazonaws.com/api/swagger-ui/index.html"
  Export:
   Name: JavaDEMOTEST
